---
plugin: netbox.netbox.nb_inventory

api_endpoint: http://10.4.198.198:8080
token: "{{ lookup('env', 'NETBOX_TOKEN') }}"
validate_certs: false

config_context: false

group_by:
  - sites
  - device_roles

query_filters:
  - status: active

compose:
  ansible_host: primary_ip4.address | default(name)
